SELECT
    YEAR(SALE.SALES_DATE) AS YEAR,
    MONTH(SALE.SALES_DATE) AS MONTH,
    INFO.GENDER AS GENDER,
    COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM
    ONLINE_SALE AS SALE
JOIN
    USER_INFO AS INFO
        ON INFO.USER_ID = SALE.USER_ID
WHERE
    INFO.GENDER IS NOT NULL
GROUP BY
    YEAR, MONTH, GENDER
ORDER BY
    YEAR ASC,
    MONTH ASC,
    GENDER ASC



