SELECT
    CAR.CAR_ID AS CAR_ID,
    CAR.CAR_TYPE AS CAR_TYPE,
    (FLOOR(CAR.DAILY_FEE - (PLAN.DISCOUNT_RATE * CAR.DAILY_FEE * 0.01)) * 30) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS CAR
LEFT OUTER JOIN
    (SELECT DISTINCT
         CAR_ID
     FROM
         CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE
         '2022-11-01' BETWEEN START_DATE AND END_DATE OR
         '2022-11-30' BETWEEN START_DATE AND END_DATE OR
         START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
    ) AS RENTAL
        ON RENTAL.CAR_ID = CAR.CAR_ID
JOIN
    (SELECT
         CAR_TYPE,
         DISCOUNT_RATE
     FROM
         CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE
         DURATION_TYPE = '30일 이상'
     ) AS PLAN
        ON PLAN.CAR_TYPE = CAR.CAR_TYPE
WHERE
    CAR.CAR_TYPE IN ('세단', 'SUV') AND
    RENTAL.CAR_ID IS NULL AND
    (FLOOR(CAR.DAILY_FEE - (PLAN.DISCOUNT_RATE * CAR.DAILY_FEE * 0.01)) * 30) 
        BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC,
    CAR_TYPE,
    CAR_ID DESC