SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RENTAL
WHERE
    DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10' AND
    (SELECT
         COUNT(*)
     FROM
         CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE
         DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10' AND
         CAR_ID = RENTAL.CAR_ID) >= 5
GROUP BY
    MONTH, CAR_ID
HAVING
    RECORDS != 0
ORDER BY
    MONTH ASC,
    CAR_ID DESC