WITH MOST_VIEW AS (
    SELECT
        BOARD_ID
    FROM
        USED_GOODS_BOARD
    ORDER BY
        VIEWS DESC
    LIMIT 1
)

SELECT
    CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) 
        AS FILE_PATH
FROM
    MOST_VIEW AS MOST
JOIN
    USED_GOODS_FILE AS FILE
        ON MOST.BOARD_ID = FILE.BOARD_ID
ORDER BY
    FILE.FILE_ID DESC