SELECT
    USERS.USER_ID,
    USERS.NICKNAME,
    CONCAT(USERS.CITY, ' ', USERS.STREET_ADDRESS1, ' ', USERS.STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(USERS.TLNO, 3), '-', SUBSTR(USERS.TLNO, 4, 4), '-', RIGHT(USERS.TLNO, 4))  AS 전화번호
FROM
    USED_GOODS_USER AS USERS
JOIN
    (SELECT
         COUNT(*) AS COUNTING,
         WRITER_ID
     FROM
         USED_GOODS_BOARD
     GROUP BY
         WRITER_ID) AS BOARD
        ON BOARD.WRITER_ID = USERS.USER_ID
WHERE
    COUNTING >= 3
ORDER BY
    USERS.USER_ID DESC