SELECT
    HALF.FLAVOR
FROM
    FIRST_HALF AS HALF
CROSS JOIN
    (SELECT
         FLAVOR,
         SUM(TOTAL_ORDER) AS TOTAL_ORDER
       FROM
         JULY
       GROUP BY
          FLAVOR) AS SEVEN
        ON HALF.FLAVOR = SEVEN.FLAVOR
GROUP BY
    FLAVOR
ORDER BY
    SUM(HALF.TOTAL_ORDER) + SEVEN.TOTAL_ORDER DESC
LIMIT 3