SELECT
    CUSTOMER.USER_ID,
    CUSTOMER.NICKNAME,
    SUM(BOARD.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS BOARD
JOIN
    USED_GOODS_USER AS CUSTOMER
        ON BOARD.WRITER_ID = CUSTOMER.USER_ID
WHERE
    BOARD.STATUS = 'DONE'
GROUP BY 
    CUSTOMER.USER_ID
HAVING
    TOTAL_SALES >= 700000
ORDER BY 
    TOTAL_SALES ASC