WITH EXPENSIVE_FOOD AS (
    SELECT DISTINCT
        CATEGORY,
        MAX(PRICE) AS PRICE
    FROM
        FOOD_PRODUCT
    GROUP BY
        CATEGORY
)

SELECT
    FOOD.CATEGORY,
    FOOD.PRICE AS MAX_PRICE,
    FOOD.PRODUCT_NAME
FROM
    FOOD_PRODUCT AS FOOD
JOIN
    EXPENSIVE_FOOD AS EXP
        ON EXP.PRICE = FOOD.PRICE AND
           EXP.CATEGORY = FOOD.CATEGORY
WHERE
    FOOD.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY
    MAX_PRICE DESC 