SELECT
    MEMBER.MEMBER_NAME,
    REVIEW.REVIEW_TEXT AS REVIEW_TEXT,
    DATE_FORMAT(REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    (SELECT 
         MEMBER_ID, 
         COUNT(*) AS AMOUNT 
     FROM 
         REST_REVIEW 
     GROUP BY 
         MEMBER_ID
     ORDER BY 
         AMOUNT DESC
     LIMIT 1) AS MOST
JOIN
     REST_REVIEW AS REVIEW
        ON REVIEW.MEMBER_ID = MOST.MEMBER_ID
JOIN
    MEMBER_PROFILE AS MEMBER
        ON MOST.MEMBER_ID = MEMBER.MEMBER_ID
ORDER BY
    REVIEW_DATE, REVIEW_TEXT