SELECT
    BOOK.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
FROM
    BOOK
JOIN
    AUTHOR
        ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN
    BOOK_SALES
        ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE
    YEAR(BOOK_SALES.SALES_DATE) = 2022 AND
    MONTH(BOOK_SALES.SALES_DATE) = 1
GROUP BY
     AUTHOR.AUTHOR_ID, BOOK.CATEGORY
ORDER BY
    BOOK.AUTHOR_ID ASC,
    BOOK.CATEGORY DESC