SELECT
    PRODUCT.PRODUCT_CODE AS PRODUCT_CODE,
    SUM(SALE.SALES_AMOUNT) * PRODUCT.PRICE AS SALES
FROM
    OFFLINE_SALE AS SALE
JOIN
    PRODUCT
        ON PRODUCT.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY
    SALE.PRODUCT_ID
ORDER BY
    SALES DESC, PRODUCT_CODE