SELECT
    HISTORY.HISTORY_ID,
    ROUND(CAR.DAILY_FEE - IFNULL((
        SELECT
            DISCOUNT_RATE
        FROM
            CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE
            CAR_TYPE = '트럭' AND
            DURATION_TYPE = CASE
                WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 7 THEN '7일 이상'
            END), 0) * CAR.DAILY_FEE * 0.01) * (DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1)
            AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
JOIN
    CAR_RENTAL_COMPANY_CAR AS CAR
        ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE
    CAR.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC,
    HISTORY_ID DESC


