SELECT
    PRODUCT.PRODUCT_ID,
    PRODUCT.PRODUCT_NAME,
    SUM(FOOD_ORDER.AMOUNT) * PRODUCT.PRICE AS TOTAL_SALES
FROM
    FOOD_ORDER
JOIN
    FOOD_PRODUCT AS PRODUCT
        ON FOOD_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
WHERE
    YEAR(FOOD_ORDER.PRODUCE_DATE) = 2022 AND
    MONTH(FOOD_ORDER.PRODUCE_DATE) = 5
GROUP BY 
    PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID