SELECT
    AP.APNT_NO AS APNT_NO,
    P.PT_NAME,
    P.PT_NO,
    AP.MCDP_CD,
    D.DR_NAME,
    AP.APNT_YMD
FROM
    APPOINTMENT AS AP
JOIN
    PATIENT AS P
        ON P.PT_NO = AP.PT_NO
JOIN
    DOCTOR AS D
        ON D.DR_ID = AP.MDDR_ID
WHERE
    AP.MCDP_CD = 'CS' AND
    DATE_FORMAT(AP.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND
    (AP.APNT_CNCL_YN = 'N' OR DATE_FORMAT(AP.APNT_YMD, '%Y-%m-%d') > '2022-04-13')
ORDER BY
    APNT_YMD