SELECT DISTINCT
    CAR.CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
JOIN
    CAR_RENTAL_COMPANY_CAR AS CAR
        ON HISTORY.CAR_ID = CAR.CAR_ID
WHERE
    CAR.CAR_TYPE = '세단' AND
    MONTH(START_DATE) = 10
ORDER BY
    CAR_ID DESC