SELECT
    INFO.REST_ID,
    INFO.REST_NAME,
    INFO.FOOD_TYPE,
    INFO.FAVORITES,
    INFO.ADDRESS,
    ROUND(AVG(REVI.REVIEW_SCORE), 2) AS SCORE
FROM 
    REST_INFO AS INFO
INNER JOIN
    REST_REVIEW AS REVI
ON
    REVI.REST_ID = INFO.REST_ID
WHERE
    INFO.ADDRESS LIKE "서울%"
GROUP BY
    INFO.REST_ID
ORDER BY
    SCORE DESC, INFO.FAVORITES DESC